git:
  submodules: false
language: perl
os:
  - linux
  - osx
perl:
  - "5.24"
  - "5.14"
  - "5.10"
before_install: git submodule update --init
install: "make test-deps"
script: "make test-main"
notifications:
  email:
    - wakaba@suikawiki.org
  irc:
    channels:
      - "ircs://irc.suikawiki.org:6697#mechanize"
    use_notice: true
env:
  global:
    secure: "OEvAJC8+oKq1P26Aaw/H4eh0xjC+kd06ZRMdTHXnaF3KFtTwZoijGjkuZ0SD6ejDblX1vFAbAujCBpejOqin65FGP2dMy/dGcHdBWKgOlbqCuW5Yuw+JhnS8ot4/9tuBEVut36n9pMTNw6eAywlI0YKmqQ5WoEzR8TlSSAxdhTFhJlXrS53TuLcy2Lp9X3U2REm6gzhJmLuqLsYB3J0s2q4HAr8+PN9aJ7I+SINluTRuW17P5a2/6dS+zd8EiWKAaNO5Plf4H7XH58c8XSYbY1rBMfctPrDTlOcw5UoV7lqTM8mfIV2idhTZCBlUCkT15kxPXkAy4ClXnaIr23+pgqZPewftHjOyio5RYPsPRT0c6Av1VqwVmNOtzkoQi84z9Ox+KGDaExAhm14nu4yni9eUmGDwtaN1bNK+AMRodPkIv0BKrl4Q9n4wWtNQfj8WmHLHliRTPGXLRBVmRZokgFbyqN6CSijKN+j2WDBXZuH6ad3PKWUI2BfHUX/+Ve7pO+/hMWWzToFcFW/D2tjSW7D3eu7el6XRdTKO+H1qsBNs2e/r6I/jzSZGObRyf4rs9LXlLcqzAmI6Ck8gpiHZaEbSNOdFch+TqfkN8lQnJO6UepasYR8NkW0YWEad6mpdmvyBJdIqiGKERiaQVa3XXGcf5TRp9AyaGhNPG0wWHq4="
after_success:
  - curl -s -S -L https://gist.githubusercontent.com/wakaba/9970857/raw/travis-merger.pl | perl
